import {
  ChartArea,
  FileStack,
  LucideIcon,
  MessageCircleQuestionMark,
  SearchX,
} from "lucide-react";
import { Checkbox } from "../ui/checkbox";
import { Label } from "../ui/label";
import CollectionFields from "./collection_fields";
import CollectionIdentity from "./identity";
import { useState } from "react";
import {
  noHitsQueriesCollectionFields,
  queryAnalyticsWithMetaFieldsCollectionFields,
  querySuggestionCollectionFields,
  ragConversationHistoryCollectionFields,
} from "@/config/template_conllection_fields";
import { useCreateCollectionForm } from "./collection_create_assembly";
import Link from "next/link";
import { DocumentationLinks } from "@/config/documentaion_links";

const templates = [
  {
    id: "query_suggestion",
    icon: MessageCircleQuestionMark,
    title: "Query Suggestions Collection",
    description:
      "Collection to which search queries will be aggregated and logged to.",
    fields: querySuggestionCollectionFields,
    url: DocumentationLinks.querySuggestionCollectionTemplate,
  },
  {
    id: "query_analytics",
    icon: ChartArea,
    title: "Query Analytics with Meta Fields Collection",
    description:
      "Collection for tracking additional metadata along with search queries for analytics purposes.",
    fields: queryAnalyticsWithMetaFieldsCollectionFields,
    url: DocumentationLinks.queryAnalyticsWithMetaFieldsCollectionTemplate,
  },
  {
    id: "no_hits_query",
    icon: SearchX,
    title: "No hits queries Collection",
    description:
      "Collection that allows for tracking of queries that produced no hits.",
    fields: noHitsQueriesCollectionFields,
    url: DocumentationLinks.noHitsQueriesCollectionTemplate,
  },
  {
    id: "rag_conversaion_history",
    icon: FileStack,
    title: "RAG Conversation History Collection",
    description:
      "Stores conversation histories generated by the conversational search feature",
    fields: ragConversationHistoryCollectionFields,
    url: DocumentationLinks.ragConversationHistoryCollectionTemplate,
  },
];

const TemplateCollections = () => {
  const { setValue } = useCreateCollectionForm();

  const [selected, setSelected] = useState<string | undefined>();
  const handleCheckboxChange = (checked: boolean, id: string) => {
    if (checked) {
      setSelected(id);
      setValue("fields", templates.find((t) => t.id === id)?.fields ?? []);
    } else {
      setValue("fields", []);
      setSelected(undefined);
    }
  };

  return (
    <div>
      <p className="font-mono my-2">
        These are collections automatically populated by typesense for various
        purposes.
      </p>
      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5 my-5">
        {templates.map(({ icon, description, title, id, url }, index) => (
          <SingleCollectionTemplate
            key={index}
            id={id}
            Icon={icon}
            title={title}
            description={description}
            checked={id === selected}
            onCheckedChange={(checked, id) => {
              handleCheckboxChange(checked, id);
            }}
            link={url}
          />
        ))}
      </div>
      <CollectionIdentity />
      <CollectionFields collectionCreationMethod="template" />
    </div>
  );
};

const SingleCollectionTemplate = ({
  description,
  Icon,
  title,
  checked,
  onCheckedChange,
  id,
  link,
}: {
  id: string;
  Icon: LucideIcon;
  title: string;
  description: string;
  checked: boolean;
  onCheckedChange: (checked: boolean, id: string) => void;
  link: string;
}) => {
  return (
    <Label className="font-mono hover:bg-accent/50 flex items-start gap-3 rounded-lg border p-3 has-aria-checked:border-blue-600 has-aria-checked:bg-blue-50 dark:has-aria-checked:border-blue-900 dark:has-aria-checked:bg-blue-950">
      <Checkbox
        id={id}
        defaultChecked={false}
        checked={checked}
        onCheckedChange={(e) => {
          onCheckedChange(Boolean(e.valueOf()), id);
        }}
        className="data-[state=checked]:border-blue-600 data-[state=checked]:bg-blue-600 data-[state=checked]:text-white dark:data-[state=checked]:border-blue-700 dark:data-[state=checked]:bg-blue-700"
      />
      <div className="grid gap-2 font-normal">
        <Icon size={30} className="mb-2" />
        <p className="text-sm leading-none font-medium">{title}</p>
        <p className="text-muted-foreground text-sm line-clamp-4">
          {description}
        </p>
        <p className="font-mono">
          Read more{" "}
          <span className="text-blue-500">
            <Link target="_blank" href={link}>
              here
            </Link>
          </span>
        </p>
      </div>
    </Label>
  );
};

export default TemplateCollections;
