---
services:
  admin_dashboard:
    container_name: admin_dashboard
    # If you want to use the image from the registry, uncomment the following line
    # image: ghcr.io/lewynation/docker-dash:latest # Confirm the latest image tag

    # And comment the following build context lines
    build:
      context: .
    # end
    restart: always
    environment:
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=5acd25d4b79182aeca70db52093facc7

    ports:
      - 3005:3000
