const initialState = [
  {
    value: "collections",
    parentDescription: "Allow all kinds of collection related operations.",
    label: "Collections",
    selected: false,
    allowsAllOperations: true,
    children: [
      {
        value: "collections:create",
        label: "collections:create",
        description: "Allows a collection to be created.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "collections:delete",
        label: "collections:delete",
        description: "Allows a collection to be deleted.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "collections:get",
        label: "collections:get",
        description: "Allows a collection schema to be retrieved.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "collections:list",
        label: "collections:list",
        description: "Allows retrieving all collection schema.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "documents",
    label: "Documents",
    parentDescription: "Allows all document operations.",
    selected: false,
    allowsAllOperations: true,
    children: [
      {
        value: "documents:search",
        label: "documents:search",
        description: "Allows only search requests.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "documents:get",
        label: "documents:get",
        description: "Allows fetching a single document.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "documents:create",
        label: "documents:create",
        description: "Allows creating documents.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "documents:upsert",
        label: "documents:upsert",
        description: "Allows upserting documents.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "documents:update",
        label: "documents:update",
        description: "Allows updating documents.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "documents:delete",
        label: "documents:delete",
        description: "Allows deletion of documents.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "documents:import",
        label: "documents:import",
        description: "Allows import of documents in bulk.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "aliases",
    label: "Aliases",
    parentDescription: "Allows all alias operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "aliases:list",
        label: "aliases:list",
        description: "Allows all aliases to be fetched.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "aliases:get",
        label: "aliases:get",
        description: "	Allows a single alias to be retrieved",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "aliases:create",
        label: "aliases:create",
        description: "	Allows the creation of aliases.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "aliases:delete",
        label: "aliases:delete",
        description: "	Allows the deletion of aliases.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "synonyms",
    label: "Synonyms",
    parentDescription: "Allows all synonym operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "synonyms:list",
        label: "synonyms:list",
        description: "Allows all synonyms to be fetched.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "synonyms:get",
        label: "synonyms:get",
        description: "Allows a single synonym to be retrieved",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "synonyms:create",
        label: "synonyms:create",
        description: "Allows the creation of synonyms.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "synonyms:delete",
        label: "synonyms:delete",
        description: "Allows the deletion of synonyms.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "overrides",
    label: "Overrides",
    parentDescription: "Allows all override operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "overrides:list",
        label: "overrides:list",
        description: "	Allows all overrides to be fetched.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "overrides:get",
        label: "overrides:get",
        description: "Allows a single override to be retrieved",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "overrides:create",
        label: "overrides:create",
        description: "Allows the creation of overrides.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "overrides:delete",
        label: "overrides:delete",
        description: "	Allows the deletion of overrides.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "keys",
    label: "Keys",
    parentDescription: "Allows all API Key related operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "keys:list",
        label: "keys:list",
        description: "Allows fetching of metadata for all keys",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "keys:get",
        label: "keys:get",
        description: "	Allows metadata for a single key to be fetched",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "keys:create",
        label: "keys:create",
        description: "Allows the creation of API keys.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "keys:delete",
        label: "keys:delete",
        description: "Allows the deletion of API keys.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "stopwords",
    label: "Stopwords",
    parentDescription: "Allows stop words related operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "stopwords:list",
        label: "stopwords:list",
        description: "Allows all stopword sets to be fetched.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stopwords:get	",
        label: "stopwords:get	",
        description: "Allows a single stopword set to be retrieved",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stopwords:create",
        label: "stopwords:create",
        description: "Allows the creation of a stopword set.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stopwords:delete",
        label: "stopwords:delete",
        description: "Allows the deletion of a stopword set.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "misc",
    label: "Misc",
    parentDescription: "Allows these admin operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "metrics.json:list",
        label: "metrics.json:list",
        description: "Allows access to the metrics endpoint.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "debug:list",
        label: "debug:list",
        description: "Allows access to the /debug endpoint.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stats.json:list",
        label: "stats.json:list",
        description: "Allows access to the stats endpoint.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "analytics/rules",
    label: "Analytics Rules",
    parentDescription: "Allows these analytics rules operations.",
    allowsAllOperations: true,
    selected: false,
    children: [
      {
        value: "analytics/rules:list",
        label: "analytics/rules:list",
        description: "Allows all analytics rules to be fetched.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "analytics/rules:get",
        label: "analytics/rules:get",
        description: "Allows for a single analytics rule to be fetched.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "analytics/rules:create",
        label: "analytics/rules:create",
        description: "Allows the creation of analytics rules.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "analytics/rules:delete",
        label: "analytics/rules:delete",
        description: "Allows the deletion of analytics rules",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "analytics/events",
    label: "Analytics Events",
    parentDescription: "Allows these analytics rules operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "analytics/events:create",
        label: "analytics/events:create",
        description: "Allows the creation of analytics events.",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "presets",
    label: "Presets",
    parentDescription: "Allows these presets operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "presets:get",
        label: "presets:get",
        description: "Get preset (GET /presets/:name)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "presets:list",
        label: "presets:list",
        description: "List presets (GET /presets)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "presets:upsert",
        label: "presets:upsert",
        description: "Create/update preset (PUT /presets/:name)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "presets:delete",
        label: "presets:delete",
        description: "Delete preset (DELETE /presets/:name)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "stemming/dictionaries",
    label: "Stemming Dictionary",
    parentDescription: "Allows these stemming dictionary operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "stemming/dictionaries:get",
        label: "stemming/dictionaries:get",
        description: "Get stemming dictionary (GET /stemming/dictionaries/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stemming/dictionaries:list",
        label: "stemming/dictionaries:list",
        description: "List stemming dictionaries (GET /stemming/dictionaries)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stemming/dictionaries:create",
        label: "stemming/dictionaries:create",
        description:
          "Import stemming dictionary (POST /stemming/dictionaries/import)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "stemming/dictionaries:delete",
        label: "stemming/dictionaries:delete",
        description:
          "Delete stemming dictionary (DELETE /stemming/dictionaries/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "operations",
    label: "Operations",
    parentDescription: "Allows these operation operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "operations/snapshot:create",
        label: "operations/snapshot:create",
        description: "Create snapshot (POST /operations/snapshot)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "operations/vote:create",
        label: "operations/vote:create",
        description: "Vote operation (POST /operations/vote)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "operations/cache/clear:create",
        label: "operations/cache/clear:create",
        description: "Clear cache (POST /operations/cache/clear)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "operations/db/compact:create",
        label: "operations/db/compact:create",
        description: "Compact database (POST /operations/db/compact)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "operations/reset_peers:create",
        label: "operations/reset_peers:create",
        description: "Reset peers (POST /operations/reset_peers)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "operations/schema_changes:get",
        label: "operations/schema_changes:get",
        description: "Get schema changes (GET /operations/schema_changes)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "Conversation Model",
    label: "conversations/models",
    parentDescription: "Allows these Conversation Model operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "conversations/models:create",
        label: "conversations/models:create",
        description: "Create conversation model (POST /conversations/models)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "conversations/models:get",
        label: "conversations/models:get",
        description: "Get conversation model (GET /conversations/models/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "conversations/models:list",
        label: "conversations/models:list",
        description: "List conversation models (GET /conversations/models)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "conversations/models:upsert",
        label: "conversations/models:upsert",
        description:
          "Update conversation model (PUT /conversations/models/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "conversations/models:delete",
        label: "conversations/models:delete",
        description:
          "Delete conversation model (DELETE /conversations/models/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "Natural Language Search Model",
    label: "nl_search_models",
    parentDescription: "Allows these NL Search Model operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "nl_search_models:create",
        label: "nl_search_models:create",
        description: "Create NL search model (POST /nl_search_models)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "nl_search_models:get",
        label: "nl_search_models:get",
        description: "Get NL search model (GET /nl_search_models/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "nl_search_models:list",
        label: "nl_search_models:list",
        description: "List NL search models (GET /nl_search_models)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "nl_search_models:upsert",
        label: "nl_search_models:upsert",
        description: "Update NL search model (PUT /nl_search_models/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
      {
        value: "nl_search_models:delete",
        label: "nl_search_models:delete",
        description: "Delete NL search model (DELETE /nl_search_models/:id)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
  {
    value: "Configuration",
    label: "config",
    parentDescription: "Allows these Configuration operations.",
    allowsAllOperations: false,
    selected: false,
    children: [
      {
        value: "config:create",
        label: "config:create",
        description: "Update configuration (POST /config)",
        enabledBySelf: false,
        enabledByTitle: false,
      },
    ],
  },
];
export default initialState;
