import { DependencyProvider } from "@/contexts/dependency_provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DependencyProvider>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </DependencyProvider>
    </html>
  );
}
