import { DependencyProvider } from "@/contexts/dependency_provider";
import "tailwind-config/globals.css";
// import { Nunito_Sans } from "next/font/google";
import { Noto_Sans } from "next/font/google";
import { Toaster } from "ui";
import ReduxContextProvider from "@/redux/reduprovider/redux_context_provider";

const oswald = Noto_Sans({
  subsets: ["latin"],
  variable: "--oswald",
  weight: ["200", "200", "400", "300", "500", "600", "700"],
});

export const metadata = {
  title: "Typesense Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReduxContextProvider>
        <DependencyProvider>
          <body className={oswald.variable}>
            {children}
            <Toaster />
          </body>
        </DependencyProvider>
      </ReduxContextProvider>
    </html>
  );
}
