#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd website-dashboard

npx lint-staged || 
(
    echo "Something went wrong with lint-staged. Please check the error.🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️"
    false;
)

(
    echo "🤝🤝 Committing changes...🌚🌚🌚🌚"
)