#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd website-dashboard

npx lint-staged || 
(
    echo "Something went wrong with lint-staged. Please check the error.🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️"
    false;
)

(
    echo "🤝🤝 Committing changes...🌚🌚🌚🌚"
)

# to initialize husky in a monorepo: 
# npx husky install
# npx husky add .husky/pre-commit "npm test"
# then cd into the working directory and run the commands as above